context:
  label: Default
variants:
  - name: Text
    context:
      type: text
      placeholder: yourname or text
  - name: number
    context:
      type: number
      placeholder: 0123456789
  - name: password
    context:
      type: password
      placeholder: Enter your password
  - name: Email
    context:
      type: email
      placeholder: yourname@email.com
  - name: url
    context:
      type: url
      placeholder: www.example.com
  - name: tel
    context:
      type: tel
      placeholder: 0468 540 588
      pattern: "[0-9]{4}-[0-9]{3}-[0-9]{3}"
  # - name: Checkbox
  #   context: 
  #     type: checkbox
  # - name: radio
  #   context:
  #     type: radio
  - name: Date
    context:
      type: date
  - name: time
    context:
      type: time
  - name: datetime-local
    context:
      type: datetime-local
  - name: week
    context:
      type: week
  - name: month
    context:
      type: month
  - name: Color
    context:
      type: color
  - name: File
    context:
      type: file
  - name: image
    context:
      type: image
  - name: range
    context:
      type: range
  - name: search
    context:
      type: search
  - name: submit
    context:
      type: submit
  - name: reset
    context:
      type: reset
  - name: hidden
    context:
      type: hidden